name: jobsearch
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - pyarrow
  - numpy
  - python-docx
  - pypdf2
  - pydantic
  - python-dateutil
  - google-generativeai
  - pip
  - pip:
    - perplexityai

